twig:
    file_name_pattern: '*.twig'

    globals:
        version: '%env(VERSION)%'
        push_notification_vapid_public_key: '%env(VAPID_PUBLIC_KEY)%'

when@test:
    twig:
        strict_variables: true
