# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: fr
    app_locales: fr|en
    default_uri: '%env(ROUTER_REQUEST_CONTEXT_SCHEME)%://%env(ROUTER_REQUEST_CONTEXT_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            string $env: '%kernel.environment%'
            string $defaultUri: '%default_uri%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/AppContext/'
        exclude:
            - '../src/AppContext/{Domain/Model}'
            - '../src/AppContext/Kernel.php'

    Front\:
        resource: '../src/FrontContext/'
        exclude:
            - '../src/FrontContext/{Domain/Model}'

    Panel\:
        resource: '../src/PanelContext/'
        exclude:
            - '../src/PanelContext/{Domain/Model}'

    Security\:
        resource: '../src/SecurityContext/'
        exclude:
            - '../src/SecurityContext/{Domain/Model}'

    Signature\:
        resource: '../src/SignatureContext/'
        exclude:
            - '../src/SignatureContext/{Domain/Model}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
